// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package vgpu

const (
	Version     = "v1.0.34"
	GitCommit   = "df0c7de"          // the commit JUST BEFORE the release
	VersionDate = "2023-09-25 05:40" // UTC
)
